### ISSUE TITLE
Registration fails with python extension

### ISSUE THREAD

**Issue by omartijn** [duo-labs/py_webauthn#25]
Traceback (most recent call last):
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/martijn/git/py_webauthn/flask_demo/app.py", line 130, in verify_credential_info
    challenge = session['challenge']
  File "/home/martijn/.local/lib/python3.5/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/home/martijn/.local/lib/python3.5/site-packages/flask/sessions.py", line 83, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'challenge'

**Comment by futureimperfect** [comment]
Hi @omartijn,

Thanks for bringing this to our attention! Can you give me a bit more information about how you encountered this error. Are you running the Flask demo as-is?

Thanks!

**Comment by futureimperfect** [comment]
Hey @omartijn,

Any update on this? Thanks!

**Comment by futureimperfect** [comment]
Hi @omartijn,

I'm going to close this out for now since I haven't heard back and I'm unable to reproduce. Feel free to reopen if you're still having the problem!

**Comment by omartijn** [comment]
I have no idea how, but I completely missed your first message. Sorry about that. I encountered the error running the demo as-is. I ran it on a debian stretch system with Firefox 60.6 esr and a yubikey.
