### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Lucid-Network** [duo-labs/py_webauthn#30]
Hello,

I downloaded the zip into a folder on my mac, then I followed your suggestions to run the demo. The html form does appear on the localhost:5000, but when I enter my name and my Display Name and hit the reg button, the terminal throws out this:

Traceback (most recent call last):
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/irre/dev/webauthn/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/irre/dev/webauthn/app.py", line 90, in webauthn_begin_activate
    make_credential_options = webauthn.WebAuthnMakeCredentialOptions(
AttributeError: module 'webauthn' has no attribute 'WebAuthnMakeCredentialOptions'

Nothing else happens. What should I do? thx

**Comment by futureimperfect** [comment]
Hi @Lucid-Network,

Did you create the `webauthn` directory in your `dev` folder? Can you try renaming the directory? I suspect the Python interpreter assumes your directory is the `webauthn` package.

Thanks!

**Comment by Lucid-Network** [comment]
Ok yes, sticking to the original folder structure solves this. Now the server shows me the post request.

127.0.0.1 - - [01/Apr/2019 19:01:21] "POST /webauthn_begin_activate HTTP/1.1" 200 -

Now I struggle with the "Try registering and logging in with a compatible U2F or WebAuthn authenticator."

So a hardware dongle is required or is there an App that would also work? Thank you!
